services:
  frontend:
    build: ./frontend
    env_file:
    - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    env_file:
    - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/generated
      - ./backend/src/firebase/serviceAccountKey.json:/app/src/firebase/serviceAccountKey.json
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/financeiro"

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: financeiro
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: